---
kind: pipeline
name: default

steps:
  - name: lint
    image: golangci-lint
    commands:
      - golangci-lint run --enable-all
  - name: test
    image: golang
    commands:
      - go build
      - go test -v
